<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Sitzung 9: Inferenzstatistik – Kontraste</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="icon" type="image/png" href="favicon.ico"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.min.js" type="text/javascript"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Seminar Quantitative Methoden</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="glyphicon glyphicon-book"></span>
     
    Quantitative Methoden I
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Material</li>
    <li>
      <a href="page-q1_materials.html">Übungsdatensätze</a>
    </li>
    <li class="divider"></li>
    <li class="divider"></li>
    <li class="dropdown-header">Einführung</li>
    <li>
      <a href="page-01einfuehrung.html">Sitzung 1: Arbeiten mit MS Excel</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Deskriptive Statistik</li>
    <li>
      <a href="page-02datenaufb.html">Sitzung 2: Umfragen und Experimente - Datenaufbereitung</a>
    </li>
    <li>
      <a href="page-03deskriptiv.html">Sitzung 3: Deskriptive Datenanalyse und Grafiken</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Inferenzstatistik</li>
    <li>
      <a href="page-04wsk_vert.html">Sitzung 4: Arbeiten mit Wahrscheinlichkeitsverteilungen</a>
    </li>
    <li>
      <a href="page-05m_se_ki.html">Sitzung 5: Mittelwerte, Standardfehler und Konfidenzintervall</a>
    </li>
    <li>
      <a href="page-06mdiffs.html">Sitzung 6: Mittelwertsunterschiede prüfen - t-Tests</a>
    </li>
    <li>
      <a href="page-07testpl.html">Sitzung 7: G*Power zur Testplanung</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="page-zwischensitzung.html">Sithzung 8: Wiederholung/ Anwendung des bisher Gelernten</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="page-08kontraste.html">Sitzung 9: Kontraste</a>
    </li>
    <li>
      <a href="page-09wilcoxon.html">Sitzung 10: Wilcoxon-Tests</a>
    </li>
    <li>
      <a href="page-10korrelz.html">Sitzung 11: Korrelationen und z-Test</a>
    </li>
    <li>
      <a href="page-11chisquared.html">Sitzung 12: Analyse von Nominaldaten</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="glyphicon glyphicon-book"></span>
     
    Quantitative Methoden II
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Material</li>
    <li>
      <a href="page-q2_materials.html">Video Links und Daten</a>
    </li>
    <li class="divider"></li>
    <li class="divider"></li>
    <li class="dropdown-header">Wiederholung</li>
    <li>
      <a href="q2_html_pages/Wiederholung1.html">Sitzung 2: Skript zu Video Teil 1 und 2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Sitzung 9: Inferenzstatistik – Kontraste</h1>

</div>


<p>In Sitzung 6 haben Sie gelernt, wie man mittels t-Tests Mittelwertsunterschiedshypothesen testen kann. Die Hypothesen bezogen sich dabei immer auf die Unterschiede zwischen maximal zwei Mittelwerten (z.B. Unterscheiden sich die Cholesterinwerte von Personen, die sich vegan ernähren, von denen von Personen, die sich nicht vegan ernähren.). Was aber, wenn sich eine Hypothese auf mehr als zwei Mittelwerte bezieht? In dieser Sitzung sollen Sie die Kontrastanalyse und die Trendanalyse als ein mögliches statistisches Verfahren für diesen Fall kennenlernen. Diese Analysen können als eine Erweiterung des T-Tests für den Fall von mehr als zwei Mittelwerten betrachtet werden. Andersherum könnte man auch sagen, dass der t-Test ein Spezialfall der Kontrastanalyse für den Unterschied von zwei Mittelwerten ist (dazu später mehr).</p>
<p>In dieser Sitzung beschäftigen wir uns mit Kontrast- bzw. Trendanalysen für den <em>einfaktoriellen Fall</em> (d.h., für Fälle, in denen es nur eine UV bzw. Prädiktorvariable gibt). Im Sommersemester werden wir auch Kontrastanalysen für mehrfaktorielle und Versuchsdesigns kennenlernen.</p>
<p><br></p>
<div id="szenario-bildung-von-antikörpern-durch-schutzimpfung" class="section level1">
<h1><span class="header-section-number">1</span> Szenario: Bildung von Antikörpern durch Schutzimpfung</h1>
<p>Stellen Sie sich folgendes Szenario vor: Ein neuartiges Virus verbreitet sich und mögliche Impfstoffe befinden sich derzeitig noch in der Entwicklung. Die VirologInnen eines Forschungsinstituts haben kürzlich eine erste klinische Wirksamkeitsstudie für einen potenziellen Impfstoff durchgeführt, nachdem sich dieser in vorangegangenen Tierversuchen bereits als vielversprechend gezeigt hatte. An der Studie nahmen 180 Versuchspersonen teil, die zufällig in drei verschiedene Gruppen mit jeweils 60 ProbandInnen aufgeteilt wurden. Die erste Gruppe bekam lediglich einen Placebo (Kochsalzlösung) injiziert. Die beiden anderen Gruppen bekamen jeweils den Impfstoff injiziert, allerdings in verschiedenen Dosen. Die erste Impfgruppe bekam eine Dosis von 0.15 ml injiziert. Die zweite Gruppe bekam die Doppelte Dosis (0.30 ml) injiziert. Nach 14 Tagen wurde bei allen Versuchspersonen die Menge von Antikörpern im Blut gemessen. Gemessen wurde die Immunglobinkonzentration (in g/l). Es wird vermutet, dass die Immunglobinkonzentration mindestens 1.5 g/l betragen muss, wenn ein Impfstoff erfolgreich gegen das Virus schützen soll.</p>
<p>Die ForscherInnen haben folgende Hypothesen aufgestellt:</p>
<ol style="list-style-type: decimal">
<li><p>Impfstoffeffekt: Bei einer Injektion mit Impfstoff ist die Immunglobinkonzentration höher als bei Injektion des Placebos.</p></li>
<li><p>Dosierungseffekt: Wenn 0.30 ml Impfstoff injiziert werden, ist die Immunglobinkonzentration höher, als wenn nur 0.15 ml Impfstoff injiziert werden.</p></li>
<li><p>Schwelleneffekt: Die Injektion von 0.30 ml wird zu einer ausreichenden Immunglobinkonzentration führen, aber eventuell reicht auch schon die kleinere Dosis.</p></li>
</ol>
<p>Die Excel-Datei mit den Daten der Studie finden Sie <a href="q1_dataFiles/08_Kontraste.xlsx">hier</a>.</p>
<p>Unten sehen sie eine Abbildung (die man in der Form so leider nicht in Excel erstellen kann), die die Ergebnisse der Studie zusammenfasst. Die roten Punkte sind die Gruppenmittelwerte (Fehlerbalken = 95% KI) und die blauen Kreuze die Mediane. Die grauen Punkte sind die Immunglobinwerte der jeweiligen Versuchspersonen. Die “Violinplots” (s. <a href="https://towardsdatascience.com/violin-plots-explained-fb1d115e023d">hier</a>) beschreiben die Verteilung der Daten. Die horizontale schwarze Linie bei 1.5 g/l zeigt den Schwellenwert für eine ausreichende Immunglobinkonzentration an. Unter der Abbildung sehen Sie noch eine Tabelle mit deskriptiven Statistiken.</p>
<p>Anhand dieser Abbildung können Sie die dritte Hypothese bereits beantworten. Eine Impfdosis von 0,30 ml scheint ausreichend zu sein, während eine Dosis von 0.15 ml zu klein ist.</p>
<p>Um die Hypothesen 1) und 2) zu testen, führen wir im Folgenden eine Kontrastanalyse durch.</p>
<p><br></p>
<p><img src="page-08kontraste_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto auto auto 0;" /></p>
<pre><code>## : Placebo
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##   0.50420000   0.51312500   0.02350586   0.04703512   0.03315153   0.18207562   0.35483678 
## ---------------------------------------------------------------------------------------------------------------- 
## : 0.15 ml
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##   0.93055000   0.94305667   0.02279833   0.04561935   0.03118583   0.17659509   0.18725820 
## ---------------------------------------------------------------------------------------------------------------- 
## : 0.30 ml
##       median         mean      SE.mean CI.mean.0.95          var      std.dev     coef.var 
##   1.88945000   1.89701167   0.02723980   0.05450671   0.04452040   0.21099858   0.11122682</code></pre>
<p><br></p>
</div>
<div id="kontrastanalyse" class="section level1">
<h1><span class="header-section-number">2</span> Kontrastanalyse</h1>
<p>Ein “Kontrast” <span class="math inline">\(D\)</span> ist die Summe <em>gewichteter Mittelwerte</em>. Bei der Kontrastanalyse wird getestet, wie wahrscheinlich ein empirisch ermittelter Wert von <span class="math inline">\(D\)</span> (oder ein noch extremerer Wert) gefunden wird, wenn der wahre Wert von <span class="math inline">\(D\)</span> null ist (dieses Prinzip sollte Ihnen bekannt vorkommen). Übersetzen wir die von den ForscherInnen aufgestellten Hypothesen zunächst in statistische Hypothesenpaare über Kontraste.</p>
<p><br></p>
<div id="statistische-hypothesen" class="section level2">
<h2><span class="header-section-number">2.1</span> Statistische Hypothesen</h2>
<p>Die erste Hypothese war, dass eine Impfung mit Impfstoff zu höherer Antikörperkonzentration führt als die Injektion eines Placebos:</p>
<ul>
<li>H1,1: <span class="math inline">\(\Delta &gt; 0\)</span> vs. H0,1: <span class="math inline">\(\Delta \leq 0\)</span>.</li>
</ul>
<p>Die zweite Hypothese war, dass die höhere Impfdosis zu einer höheren Antikörperkonzentration führt, als die niedrige Dosis:</p>
<ul>
<li>H1,2: <span class="math inline">\(\Delta &gt; 0\)</span> vs. H0,2: <span class="math inline">\(\Delta \leq 0\)</span>.</li>
</ul>
<p><br></p>
</div>
<div id="berechnung-des-empirischen-d-und-der-teststatistik-t-wert" class="section level2">
<h2><span class="header-section-number">2.2</span> Berechnung des empirischen D und der Teststatistik (t-Wert)</h2>
<p>Berechnen wir nun die empirischen D-Werte und die dazugehörigen Teststatistiken (t-Werte). Wie oben bereits angesprochen wurde, handelt es sich bei Kontrasten um die Summe gewichteter Mittelwerte. Ganz zu Beginn wurde auch erwähnt, dass der t-Test als Spezialfall eines Kontrasts angesehen werden kann, bei dem nur zwei Mittelwerte verglichen bzw. <em>kontrastiert</em> werden.</p>
<p>Um zu verdeutlichen, was mit “Summe gewichteter Mittelwerte” gemeint ist, und um zu sehen, warum der “klassische” t-Test eigentlich ein Spezialfall der Kontrastanalyse ist, beginnen wir unsere Analyse mit der zweiten Hypothese, in der die Mittelwerte der beiden Impfgruppen gegeneinander getestet werden sollen.</p>
<p><br></p>
<div id="zähler-der-t-formel-ist-ein-kontrast-d" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Zähler der t-Formel ist ein Kontrast (D)</h3>
<p><strong>Hohe Impfdosis vs. niedrige Impfdosis:</strong></p>
<p>In der Versuchsgruppe, in der 0.30 ml Impfstoff injiziert wurden, beträgt die mittlere Immunglobinkonzentration <span class="math inline">\(M~= 1.9\)</span> g/l. In der Versuchsgruppe mit 0.15 ml Impfstoff ist die mittlere Konzentration niedriger, nämlich <span class="math inline">\(M~= 0.94\)</span> g/l. Um zu prüfen, wie plausibel es ist, dass dieser Stichprobenunterschied einfach nur Zufall ist, würden Sie nun eigentlich einen t-Test durchführen und dabei den empirischen t-Wert folgendermaßen ermitteln:</p>
<p><span class="math inline">\(t~= \frac{M_{0.30 ml} - M_{0.15ml}}{SE_{Diff}}\)</span>.</p>
<p>Im Zähler der t-Formel steht die Differenz der beiden Stichprobenmittelwerte. Diese Differenz ist tatsächlich ein Kontrast (<span class="math inline">\(D\)</span>), denn diese Differenz lässt sich auch als “Summe gewichteter Mittelwerte” ausdrücken:</p>
<p><span class="math inline">\(t~= \frac{(1\cdot M_{0.30 ml}) + (-1 \cdot M_{0.15ml})}{SE_{Diff}}~= \frac{D}{SE_{Diff}}\)</span>.</p>
<p>In der obigen Formel werden beide Mittelwerte gleichstark (mit <span class="math inline">\(|1|\)</span>) gewichtet. Allerdings bekommt der zweite Mittelwert ein negatives Gewicht (<span class="math inline">\(-\)</span>). Die Summe der beiden auf diese Weise gewichteten Mittelwerte (der Kontrast <span class="math inline">\(D\)</span>) ist dann identisch zur Mittelwertsdifferenz (was Sie sehen, wenn sie die Klammern wieder auflösen). <br></p>
</div>
<div id="mehr-als-zwei-mittelwerte" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Mehr als zwei Mittelwerte</h3>
<p>Schauen wir uns nun die erste Hypothese der ForscherInnen an, die besagt, dass eine Impfung mit Impfstoff zu mehr Antikörpern führt als die Impfung mit Placebo. In dieser Hypothese wird nichts über die Konzentration des Impfstoffs gesagt, d.h., wir können nicht einfach den Mittelwert von einer der Beiden Impfgruppen verwenden und mittels (einfachem) t-Test gegen den Mittelwert der Placebogruppe testen. Stattdessen müssen wir beide Impfgruppen kombinieren und gegen die Placebogruppe vergleichen.</p>
<p><strong>Impfung vs. Placebo:</strong></p>
<p>Diese Hypothese lässt sich folgendermaßen als Summe gewichteter Mittelwerte (<span class="math inline">\(D\)</span>) ausdrücken:</p>
<p><span class="math inline">\(D~= (c_1 \cdot M_{0.30ml}) + (c_2 \cdot M_{0.15ml}) + (c_3 \cdot M_{Placebo})\)</span>.</p>
<p>Die <span class="math inline">\(c\)</span> stehen dabei für die <em>Kontrastgewichte</em> bzw. <em>Kontrastkoeffizienten</em>. Oben beim einfachen t-Tests waren die Werte von <span class="math inline">\(c\)</span> einmal <span class="math inline">\(1\)</span> und einmal <span class="math inline">\(-1\)</span>. Für die erste Hypothese, die sich auf den Unterschied zwischen Impfung und Placebo bezieht, vergeben wir nun folgende Werte für <span class="math inline">\(c\)</span>:</p>
<p><span class="math inline">\(D~= (0.5 \cdot M_{0.30ml}) + (0.5 \cdot M_{0.15ml}) + (-1 \cdot M_{Placebo})\)</span>.</p>
<p>Der erste Teil des Terms, <span class="math inline">\((0.5 \cdot M_{0.30ml}) + (0.5 \cdot M_{0.15ml})\)</span> ist dann nichts anderes als der Mittelwert der beiden Mittelwerte der Impfgruppen, denn dieser Teil ließe sich ja auch so ausdrücken:</p>
<p><span class="math inline">\(\frac{1}{2} \cdot (M_{0.30ml} + M_{0.15ml})~= \frac{M_{0.30ml} + M_{0.15ml}}{2}\)</span>.</p>
<p>Also: Um die beiden Impfgruppen gegen die Placebogruppe zu testen, wird einfach der Mittelwert aus den beiden Impfgruppenmittelwerten gegen den Mittelwert der Placebogruppe getestet. <span class="math inline">\(D\)</span> drückt diesen Kontrast aus.</p>
<p><span class="math inline">\(D\)</span> hat in diesem Fall folgenden Wert:</p>
<p><span class="math inline">\(D~= (0.5 \cdot 1.897) + (0.5 \cdot 0.943) + (-1 \cdot 0.513)~= 0.949 + 0.472 - 0.513 = 0.907\)</span>.</p>
<p>Um zu beurteilen, wie wahrscheinlich dieser oder ein noch extremerer Wert von <span class="math inline">\(D\)</span> gefunden wird, wenn es in Wahrheit gar keinen Unterschied zwischen Impfung und Placebo gibt, standardisieren wir <span class="math inline">\(D\)</span> wieder so, dass die t-Verteilung zur Beurteilung der gefundenen (komplexen) Mittelwertsdifferenz verwendet werden kann. Wie Sie schon wissen - und wie wir ja oben noch einmal gesehen hatten - muss dazu die Differenz anhand des Standardfehlers der Differenz normiert werden, <span class="math inline">\(SE_{Diff}\)</span>. Die noch offene Frage ist also, wie sich <span class="math inline">\(SE_{Diff}\)</span> für diesen Fall berechnet. Die Formel lautet:</p>
<p><span class="math inline">\(SE_{Diff}~= s_{iB} \cdot \sqrt{\frac{\sum c^2_k}{n}}\)</span>.</p>
<p>Die Formel für den t-Wert für <span class="math inline">\(D\)</span> ist dementsprechend:</p>
<p><span class="math inline">\(t~= \frac{D}{s_{iB} \cdot \sqrt{\frac{\sum c^2_k}{n}}}\)</span>.</p>
<p>Im Zähler des Bruchs unter der Wurzel steht die Summe der quadrierten Kontrastkoeffizienten (<span class="math inline">\(\sum c^2_{k}\)</span>). Diese ist in unserem Fall <span class="math inline">\(0.25 + 0.25 + 1~= 1.5\)</span>.</p>
<p>Nun bleibt noch die Frage, wie man <span class="math inline">\(s_{iB}\)</span> (also die gepoolte Streuung) in diesem Fall berechnet. Die Formel ist:</p>
<p><span class="math inline">\(s_{iB}~= \sqrt{\frac{(n_1 - 1)s^2_1 + (n_2 - 1)s^2_2 + (n_3 - 1)s^2_3}{(n_1 - 1) + (n_2 - 1) + (n_3 - 1)}}\)</span>.</p>
<p>Bei gleichgroßen Stichproben vereinfacht sich die Formel durch kürzen zu:</p>
<p><span class="math inline">\(s_{iB}~= \sqrt{\frac{s^2_1 + s^2_2 + s^2_3}{3}}\)</span>.</p>
<p>die Varianzen (<span class="math inline">\(s^2\)</span>) sind in der Tabelle oben mit den deskriptiven Statistiken angegeben (“var”). Daraus ergibt sich ein Wert für <span class="math inline">\(s_{iB}\)</span> von:</p>
<pre><code>## [1] 0.1904886</code></pre>
<p>Damit können wir nun <span class="math inline">\(SE_{Diff}\)</span> berechnen, um schließlich einen empirischen t-Wert für unser <span class="math inline">\(D\)</span> zu bekommen. Der Wert für <span class="math inline">\(SE_{Diff}\)</span> ist:</p>
<pre><code>## [1] 0.03011889</code></pre>
<p>Der <span class="math inline">\(D\)</span>-Wert für die erste Hypothese entspricht also einem t-Wert von:</p>
<p><span class="math inline">\(t~= \frac{D}{s_{iB} \cdot \sqrt{\frac{\sum c^2_k}{n}}}~= \frac{0.907}{0.03011889}~= 30.11\)</span>.</p>
<p>Der dazugehörige <span class="math inline">\(p\)</span>-Wert muss aus einer t-Verteilung mit <span class="math inline">\(\sum_k(n_k-1)\)</span> Freiheitsgraden nachgeschaut werden. In unserem Fall mit drei Stichproben mit <span class="math inline">\(n~=60\)</span> ergibt das <span class="math inline">\(df~= 177\)</span>. Der <span class="math inline">\(p\)</span>-Wert ist:</p>
<pre><code>## [1] 7.479327e-72</code></pre>
<p>also praktisch <span class="math inline">\(0\)</span>. Die <span class="math inline">\(H_0\)</span> wird deshalb verworfen und die <span class="math inline">\(H_1\)</span> angenommen. Wir nehmen also an, dass eine Impfung mit Impfstoff zu mehr Antikörpern führt als eine Impfung mit Placebo.</p>
<p><strong>Hohe Impfdosis vs. niedrige Impfdosis:</strong></p>
<p>Beenden wir nun auch noch die Analyse für die zweite Kontrasthypothese, die besagte, dass die höhere Impfdosis “besser” ist als die niedrige. Wir hatten zuvor schon gesehen, dass der statistische Test in diesem Fall im Prinzip der “normale” t-Test ist. Allerdings benutzen wir hier die Streuungen aller drei Gruppen für die Bestimmung von <span class="math inline">\(s_{iB}\)</span> und nicht nur die Streuungen der zwei Gruppen, deren Mittelwerte kontrastiert werden. Wir rechnen also mit demselben <span class="math inline">\(s_{iB}\)</span> wie zuvor.</p>
<p>Der Wert für <span class="math inline">\(SE_{Diff}\)</span> ist in diesem Fall:</p>
<pre><code>## [1] 0.0347783</code></pre>
<p>Für <span class="math inline">\(D\)</span> erhalten wir einen Wert von:</p>
<p><span class="math inline">\(D~= 1.897 - 0.943~ = 0.954\)</span>.</p>
<p>Und dies entspricht einem empirischen t-Wert von:</p>
<p><span class="math inline">\(t~= \frac{D}{s_{iB} \cdot \sqrt{\frac{\sum c^2_k}{n}}}~= \frac{0.954}{0.0348}~= 27.41\)</span>.</p>
<p>Dieser Wert entspricht einem <span class="math inline">\(p\)</span> von:</p>
<pre><code>## [1] 6.707443e-66</code></pre>
<p>Auch hier verwerfen wir also die <span class="math inline">\(H_0\)</span> und nehmen die <span class="math inline">\(H_1\)</span> an. Wir gehen also davon aus, dass eine Impfung mit mehr Impfstoff tatsächlich zu mehr Antikörpfern führt als eine Impfung mit niedrigerer Konzentration des Impfstoffs.</p>
<p><br></p>
</div>
</div>
<div id="effektgröße-cohens-d" class="section level2">
<h2><span class="header-section-number">2.3</span> Effektgröße (Cohen’s d)</h2>
<p>Auch für Kontraste lassen sich standardisierte Effektgrößen, wie z.B. Cohen’s <span class="math inline">\(d\)</span> berechnen. Die Formel lautet:</p>
<p><span class="math inline">\(d~= \frac{D}{s_{iB}}\)</span>.</p>
<p>Für den Kontrast der ersten Hypothese (Impfstoffeffekt) erhalten wir eine Effektgröße von <span class="math inline">\(d~= \frac{0.907}{0.190}~= 4.77\)</span> (ein sehr großer Effekt). Für den Kontrast der zweiten Hypothese (Dosierungseffekt) erhalten wir eine Effektgröße von <span class="math inline">\(d~= \frac{0.954}{0.190}~= 5.02\)</span> (ebenfalls ein sehr großer Effekt).</p>
<p><br></p>
<div id="konfidenzintervall-für-d" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Konfidenzintervall für d</h3>
<p>Für die Effektgröße lässt sich auch ein 95%-Konfidenzintervall angeben mit:</p>
<ul>
<li>Untergrenze: <span class="math inline">\(d - 1.96 \cdot SE_d\)</span> und</li>
<li>Obergrenze: <span class="math inline">\(d + 1.96 \cdot SE_d\)</span>.</li>
</ul>
<p>Die Formel für den Standardfehler der Effektgröße ist:</p>
<p><span class="math inline">\(SE_d~= \sqrt{\frac{n_1 + n2}{n1 \cdot n_2}+ \frac{d^2}{2 \cdot (n_1 + n2)}}\)</span>.</p>
<p>Hier ist darauf zu achten, dass die <span class="math inline">\(n\)</span> für den jeweiligen Kontrast angepasst werden müssen. Schauen wir uns zur Verdeutlichung den ersten Kontrast an, bei dem die Placebogruppe gegen die beiden Impfgruppen verglichen wurde. Der Mittelwert der Placebogruppe wurde durch <span class="math inline">\(n~= 60\)</span> Versuchspersonen geschätzt. Der Mittelwert der Impfgruppen aber durch <span class="math inline">\(n~= 120\)</span> Versuchspersonen (denn in jeder der beiden Impfgruppe waren ja jeweils 60 Versuchspersonen). Entsprechend müssen wir <span class="math inline">\(n_1~= 120\)</span> und <span class="math inline">\(n_2~= 60\)</span> benutzen (wobei egal ist, welcher Wert für <span class="math inline">\(n_1\)</span> und welcher für <span class="math inline">\(n_2\)</span> eingesetzt wird). Setzen wir die entsprechenden Werte in die Formel ein, erhalten wir einen Wert für <span class="math inline">\(SE_d\)</span> von:</p>
<pre><code>## [1] 0.2969891</code></pre>
<p>Somit erhalten wir Grenzwerte von:</p>
<ul>
<li>Untergrenze: <span class="math inline">\(4.77 - 1.96 \cdot 0.297~= 4.188\)</span></li>
<li>Obergrenze: <span class="math inline">\(4.77 + 1.96 \cdot 0.297~= 5.352\)</span></li>
</ul>
<p>Für den Dosierungseffekt von <span class="math inline">\(d~= 5.02\)</span> ergibt müssen für <span class="math inline">\(n_1\)</span> und <span class="math inline">\(n_2\)</span> jeweils <span class="math inline">\(60\)</span> eingetragen werden, um <span class="math inline">\(SE_d\)</span> zu bekommen. Der Wert für <span class="math inline">\(SE_d\)</span> ist dann:</p>
<pre><code>## [1] 0.3719341</code></pre>
<p>Entsprechend erhalten wir Grenzwerte von:</p>
<ul>
<li>Untergrenze: <span class="math inline">\(5.02 - 1.96 \cdot 0.372~= 4.29\)</span></li>
<li>Obergrenze: <span class="math inline">\(5.02 + 1.96 \cdot 0.372~= 5.75\)</span></li>
</ul>
<p>Die beiden Effektgrößen und ihr Konfidenzintervall sind in der Abbildung unten noch einmal grafisch dargestellt:</p>
<p><img src="page-08kontraste_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto auto auto 0;" /> <br></p>
</div>
</div>
<div id="welche-werte-für-die-kontrastkoeffizienten-c" class="section level2">
<h2><span class="header-section-number">2.4</span> Welche Werte für die Kontrastkoeffizienten (<span class="math inline">\(c\)</span>)?</h2>
<p>Die Kontrastkoeffizienten <span class="math inline">\(c\)</span> spielen natürlich für die Größe bzw. den Wert von <span class="math inline">\(D\)</span> und auch für den Wert von <span class="math inline">\(SE_{Diff}\)</span> eine Rolle. Für die erste Hypothese, die sich auf den “Impfeffekt” bezogen hat, hatten wir Werte für <span class="math inline">\(c\)</span> von <span class="math inline">\(0.5\)</span>, <span class="math inline">\(0.5\)</span> und <span class="math inline">\(-1\)</span> genommen. Wir hätten stattdessen aber auch <span class="math inline">\(1\)</span>, <span class="math inline">\(1\)</span> und <span class="math inline">\(-2\)</span> nehmen können; wichtig ist nur, dass die Summe der Kontrastkoeffizienten <span class="math inline">\(0\)</span> ist. Beim anderen Kontrast, der ja im Grunde dem einfachen t-Test entspricht waren die Werte für <span class="math inline">\(c\)</span> <span class="math inline">\(1\)</span> und <span class="math inline">\(-1\)</span>. Hier hätten wir auch <span class="math inline">\(0.5\)</span> und <span class="math inline">\(-0.5\)</span> oder <span class="math inline">\(210\)</span> und <span class="math inline">\(-210\)</span> nehmen können. Da <span class="math inline">\(c\)</span> sowohl in der Formel für <span class="math inline">\(D\)</span> als auch in der für <span class="math inline">\(SE_{Diff}\)</span> vorkommt, hätte das am Wert für den empirischen t-Wert nichts geändert.</p>
<p>Dasselbe wie für den t-Wert gilt allerdings nicht für die Effektgröße <span class="math inline">\(d\)</span>, da hier im Nenner nur <span class="math inline">\(s_{iB}\)</span> steht, für das die Werte von <span class="math inline">\(c\)</span> keine Rolle spielen. Damit bei Kontrastanalysen die Effektstärken direkt mit denen aus “normalen” t-Tests vergleichbar sind (bei denen die Werte für <span class="math inline">\(c\)</span> ja <span class="math inline">\(1\)</span> und <span class="math inline">\(-1\)</span> sind, was eine Summe der Beträge von <span class="math inline">\(2\)</span> ergibt), ist es eine Konvention, die Werte für <span class="math inline">\(c\)</span> immer so zu vergeben, dass die Summe aller <span class="math inline">\(c\)</span>-Werte nicht nur <span class="math inline">\(0\)</span> ist, sondern die Summe der Beträge aller <span class="math inline">\(c\)</span>-Werte gleichzeitig auch <span class="math inline">\(2\)</span> ergibt:</p>
<ul>
<li><p>Notwendig: <span class="math inline">\(\sum_k c_k~= 0\)</span></p></li>
<li><p>und per Konvention: <span class="math inline">\(\sum_k |c_k|~= 2\)</span>.</p></li>
</ul>
<p><br></p>
</div>
</div>
<div id="trendanalyse" class="section level1">
<h1><span class="header-section-number">3</span> Trendanalyse</h1>
<p>Die Kontrastanalyse ist eine Möglichkeit Mittelwertsunterschiede zu prüfen, wenn mehr als zwei Stichprobenmittelwerte involviert sind. Eine andere Möglichkeit sind sogenannte Trendanalysen. Trendanalysen sind immer dann sinnvoll, wenn man eine Hypothese über den Verlauf der Mittelwerte anstellt. Wir könnten z.B. annehmen, dass die ForscherInnen erwartet haben, dass die Konzentration der Antikörper von der Placebo- über die niedrige-Dosis- bis zur hohe-Dosis-Gruppe ansteigt. Die möglichen Trends sehen Sie in der Abbildung unten:</p>
<p><br></p>
<p><img src="images/q1_08kontraste/trends.PNG" style="width:100.0%" /></p>
<p><br></p>
<p>Die letzte Art von Trend, der “kubische Trend”, ließe sich allerdings nur testen, wenn man mindestens vier Stichprobenmittelwerte vorliegen hat. In unserem Fall mit drei Stichprobenmittelwerten ließen sich also maximal quadratische Trends nachweisen.</p>
<p>Die Abbildung oben zeigt die “prototypischen” Versionen bzw. die “Reinformen” der möglichen Trends. Der lineare Trend ist z.B. eine perfekte Gerade. Die verschiedenen Trends können aber auch ineinander verschachtelt bzw. kombiniert sein. Es kann ja z.B. möglich sein, dass die Werte wie bei einem linearen Trend der Tendenz nach zunehmen (oder abnehmen im Falle eines “negativen” Trends), aber dass diese Zunahme (bzw. Abnahme) nicht gleichbleibend ist. In der Abbildung unten sehen Sie zwei Beispiele für “Mischtrends”. In der linken Abbildung z.B. ist ein <em>positiver linearer Trend</em> mit einem <em>negativen quadratischen Trends</em> kombiniert.</p>
<p><br></p>
<p><img src="images/q1_08kontraste/trends_mixed.PNG" style="width:100.0%" /></p>
<p><br></p>
<p>Eine etwas “mildere” Form der Kombination zweier Arten von Trends sehen wir übrigens auch im Verlauf der drei Mittelwerte aus unserem Beispiel. Das sieht man gut, wenn man die drei Mittelwerte noch mit einer Linie verbindet.</p>
<p><img src="page-08kontraste_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto auto auto 0;" /></p>
<p><br></p>
<p>Der Verlauf der Linie zeigt hier deutlich, dass der Abstand zwischen der Gruppe mit 0.30 ml und 0.15 ml Impfstoff größer ist, als der Abstand zwischen der Gruppe mit 0.15 ml Impfstoff und der Placebogruppe. Man könnte sagen, der Zuwachs an Antikörpern “beschleunigt” sich (ist nicht gleichbleibend). Dieser Verlauf lässt sich deshalb als Kombination eines linearen und eines quadratischen Trends beschreiben. Bei einer Trendanalyse werden beide Trendsverläufe gestestet. Wenn es wirklich stimmt, dass der Verlauf der Mittelwerte eine Kombination beider Trends ist, dann sollte die Trendanalyse signifikante Ergebnisse für einen linearen sowie für einen quadratischen Trend liefern.</p>
<p><br></p>
<div id="kontrastgewichte-für-verschiedene-trends" class="section level2">
<h2><span class="header-section-number">3.1</span> Kontrastgewichte für verschiedene Trends</h2>
<p>Die Trendanalyse ist im Grunde nichts anderes als eine Kontrastanalyse. Der Unterschied ist, dass hier die Kontrastkoeffizienten (<span class="math inline">\(c\)</span>) so vergeben werden, dass die möglichen Trends erfasst werden können. In der Tabelle unten sehen Sie die Werte, die für <span class="math inline">\(c\)</span> vergeben werden müssen und zwar in Abhängigkeit der Anzahl der vorliegenden Mittelwerte (<span class="math inline">\(k\)</span>) und der möglichen Trends bei dieser Anzahl von Mittelwerten. Die Durchführung der Analyse ist dann analog zu der oben bei den Kontrasten beschriebenen.</p>
<p><br></p>
<p><img src="images/q1_08kontraste/trends_weights.PNG" style="width:100.0%" /></p>
<p><br></p>
<p>Das Ergebnis der Trendanalysen finden Sie in der Excel-Datei in der Arbeitsmappe “Trends Lösung”. Eine Zusammenfassung der Ergebnisse sehen Sie außerdem in der nachfolgenden Tabelle:</p>
<pre><code>## 
## Call:
## aov(formula = Antibody ~ Group, data = data_long)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.45486 -0.12195 -0.00773  0.11585  0.65119 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.11773    0.01420  78.724  &lt; 2e-16 ***
## Group.L      0.97856    0.02459  39.792  &lt; 2e-16 ***
## Group.Q      0.21393    0.02459   8.699 2.25e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1905 on 177 degrees of freedom
## Multiple R-squared:  0.9036, Adjusted R-squared:  0.9025 
## F-statistic: 829.5 on 2 and 177 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Die Ergebnisse der Trendanalyse sind in dieser Darstellung die Zeilen “Group.L” (das ist der Lineare Trend) und “Group.Q” (das ist der quadratische Trend). In jeder der beiden Zeilen sehen sie die empirischen t-Werte (die dieselben sind, die Sie auch in der Excel-Arbeitsmappe finden). “Pr(&gt;|t|)” sind die entsprechenden empirischen p-Werte. Die Tabelle zeigt, dass sowohl der lineare wie auch der quadratische Trend signifikant sind (<span class="math inline">\(p\)</span> jeweils <span class="math inline">\(&lt; .05\)</span>). Es scheint also plausibel anzunehmen, dass die Antikörperkonzentration über die drei Gruppen hinweg zunimmt und dass dieser Anstieg sich über die drei Gruppen hinweg verändert (in diesem Fall wird er stärker).</p>
</div>
</div>

<p><font size="-1.5">Copyright &copy; 2020 Simon Stephan. All rights reserved.</font></p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
